# Generated by Django 4.0 on 2025-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('base_experience', models.IntegerField(verbose_name='experiencia base')),
            ],
        ),
    ]
